// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAit7xS99j3Hz5vN_tn4aJD5qxbRu5qxwo',
    appId: '1:144415162573:web:bad77d0e38f7ede6d2a984',
    messagingSenderId: '144415162573',
    projectId: 'perflist',
    authDomain: 'perflist.firebaseapp.com',
    storageBucket: 'perflist.firebasestorage.app',
    measurementId: 'G-WKCG9F35KF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvw8huxvcmAC838h0eVkWCprhNkpFpxWg',
    appId: '1:144415162573:android:8247d7c01dacc97dd2a984',
    messagingSenderId: '144415162573',
    projectId: 'perflist',
    storageBucket: 'perflist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjz2NKESncjdNGJ06GyNioi4cbwC67ZU4',
    appId: '1:144415162573:ios:6d48a086ca6c668fd2a984',
    messagingSenderId: '144415162573',
    projectId: 'perflist',
    storageBucket: 'perflist.firebasestorage.app',
    iosBundleId: 'com.example.perfList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjz2NKESncjdNGJ06GyNioi4cbwC67ZU4',
    appId: '1:144415162573:ios:6d48a086ca6c668fd2a984',
    messagingSenderId: '144415162573',
    projectId: 'perflist',
    storageBucket: 'perflist.firebasestorage.app',
    iosBundleId: 'com.example.perfList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAit7xS99j3Hz5vN_tn4aJD5qxbRu5qxwo',
    appId: '1:144415162573:web:586b2359bc02d826d2a984',
    messagingSenderId: '144415162573',
    projectId: 'perflist',
    authDomain: 'perflist.firebaseapp.com',
    storageBucket: 'perflist.firebasestorage.app',
    measurementId: 'G-0G0RTEXGW5',
  );
}
